version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    image: app
    ports:
     - "8080:8080"
     - "9229:9229"
    depends_on:
      - redis
      - mongo
    container_name: app
  redis:
    image: "redis:4.0.8-alpine"
    volumes:
        - ./data/redis:/data
    ports:
      - "6379:6379"
    container_name: redis
  mongo:
    image: "mongo:3.7-jessie"
    volumes:
        - ./data/mongo:/data/db
    ports:
        - "27017:27017"
    container_name: mongo