version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.mocha
    image: mocha
    ports:
     - "9230:9230"
    depends_on:
      - redis
      - mongo
    container_name: app
  redis:
    image: "redis:4.0.8-alpine"
    volumes:
        - ./data/test/redis:/data
    ports:
      - "6379:6379"
    container_name: redis
  mongo:
    image: "mongo:3.7-jessie"
    volumes:
        - ./data/test/mongo:/data/db
    ports:
        - "27017:27017"
    container_name: mongo

