FROM node:9.6.1-alpine

ADD package.json /tmp/package.json
ADD package-lock.json /tmp/package-lock.json
RUN cd /tmp && npm install
RUN mkdir -p /home/app && cp -a /tmp/node_modules /home/app/

ADD . /home/app
WORKDIR /home/app

RUN npm run tsc
